services:
  web:
    build: .
    ports:
      - 8080:5000
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: postgres-cont2
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - 5410:5432
    healthcheck:
      test: [ "CMD", "su", "postgres", "-c", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

