services:
  web:
    build: .
    environment:
      FLASK_RUN_HOST: ${FLASK_RUN_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USER}
    ports:
      - 8080:5000
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: postgres-cont
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USER}
    ports:
      - 5410:5432
    healthcheck:
      test: [ "CMD", "su", "postgres", "-c", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

